Fixes bug in equality operator in Token class
Currently, equality operator (==) in class Token doesn't check if the argument `other` is None, leading to the exception
```
AttributeError: 'NoneType' object has no attribute 'type'
```

This pull request fixes the bug by returning False if `other` is None